### ISSUE TITLE
AttributeError: module 'hawkey' has no attribute 'Repo'

### ISSUE THREAD

**Issue by mbooth101** [fedora-java/modularity-utils#11]
Did something change in hawkey? I'm no longer able to run the script due to:

```
Querying Koji for content of module javapackages-tools, stream 201801...                     
Loading sack...                                                        
Downloading repo primary-f30-build-1158686                        
Traceback (most recent call last):   
  File "../modularity-utils/generate-modulemd.py", line 389, in <module>
    main()                                        
  File "../modularity-utils/generate-modulemd.py", line 384, in main
    with repo_cache.RepoCache().get_sack(repo_descriptor) as sack: 
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__                                                                                                               
    return next(self.gen)                           
  File "/usr/lib/python3.7/site-packages/koschei/backend/repo_cache.py", line 86, in get_sack
    with self.get_item(repo_descriptor) as sack:           
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__      
    return next(self.gen)                        
  File "/usr/lib/python3.7/site-packages/koschei/backend/file_cache.py", line 209, in get_item                                                                                    
    item = self.create_item(cache_key, self._cachedir)
  File "/usr/lib/python3.7/site-packages/koschei/backend/repo_cache.py", line 63, in create_item
    sack = repo_util.load_sack(cachedir, repo_descriptor, download=True)     
  File "/usr/lib/python3.7/site-packages/koschei/backend/repo_util.py", line 95, in load_sack
    repo = get_repo(repo_dir, repo_descriptor, download)                 
  File "/usr/lib/python3.7/site-packages/koschei/backend/repo_util.py", line 58, in get_repo
    repo = hawkey.Repo(str(repo_descriptor))               
AttributeError: module 'hawkey' has no attribute 'Repo'
```

FWIW, on the 2nd of May my system got a new version of hawkey:

```
$ sudo dnf history info 550
Transaction ID : 550
Begin time     : Thu 02 May 2019 14:19:37 BST
Begin rpmdb    : 3526:1e00727bb9e78615eadc9d3d1e17948132d69799
End time       : Thu 02 May 2019 14:19:44 BST (7 seconds)
End rpmdb      : 3526:e4860eed638922cd90da6946269b43654c88756c
Releasever     : 29
Packages Altered:
    ....
    Upgrade  python3-hawkey-0.31.0-2.fc29.x86_64                        @updates
    Upgraded python3-hawkey-0.28.1-1.fc29.x86_64                        @@System
    ....
```

**Comment by mizdebsk** [comment]
@mbooth101 This is a regression in DNF. It should be already fixed - try installing updates-testing.

**Comment by mizdebsk** [comment]
This update should fix the problem in Fedora 29: https://bodhi.fedoraproject.org/updates/FEDORA-2019-74e1dd1341

**Comment by mbooth101** [comment]
Ah perfect, thanks.
